### ISSUE TITLE
.env not found

### ISSUE THREAD

**Issue by niyonx** [NTUEEInfoDep/NTUEEWEEKPOS#1]
Hey, I was looking for TI on docker and I found this repo https://github.com/ThisIsQasim/TastyIgniter/tree/master. However it is for v2, then I found your repo.

I tried to run it but I get 
```
 => ERROR [7/8] COPY .env /var/www/html/                                                                                             0.0s
------
 > [7/8] COPY .env /var/www/html/:
------
failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/.env" not found: not found
```

@redxouls Can you please guide me on how to prepare the .env?

**Comment by redxouls** [comment]
Thanks for bringing up this issue. I've uploaded a template file `.env.defaults` for your reference . You can also find this default generated `.env` file in the executed container if you comment out the line `COPY .env /var/www/html/ `  and run it directly.

**Comment by niyonx** [comment]
I see, it runs successfully now. I've used the same .env which is generated when I do the command-line installation. I've got another issue, I'll open a new one.
